
["Common configs for DivineRPG"]
	#Maximum stored arcana
	#Range: 200 ~ 10000
	maxArcana = 200
	#Maximum amount of loaded mobs before the frosted allure stops working
	#Range: 150 ~ 1000
	allureMaxMobs = 300

